var colors = require('../')

console.log(colors.white(37))
console.log(colors.grey(90))
console.log(colors.black(30))
console.log(colors.blue(34))
console.log(colors.cyan(36))
console.log(colors.green(32))
console.log(colors.magenta(35))
console.log(colors.red(31))
console.log(colors.yellow(33))